# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 11:59
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='picture3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='picturefigcaption1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='picturefigcaption2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='picturefigcaption3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text3',
        ),
        migrations.AlterField(
            model_name='post',
            name='capa',
            field=models.ImageField(default='static/img/logo.svg', help_text='Resolução recomendada: 800x600 horizontal', upload_to='img/', verbose_name='Foto da capa'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text1',
            field=ckeditor.fields.RichTextField(verbose_name='Conteúdo'),
        ),
    ]
