# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 12:01
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161116_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='capa',
            field=models.ImageField(default='blog/img/logo.svg', help_text='Resolução recomendada: 800x600 horizontal', upload_to=blog.models.path_and_rename, verbose_name='Foto da capa'),
        ),
    ]
