# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161116_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text1',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='aa'),
            preserve_default=False,
        ),
    ]
