# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 17:33
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161116_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnviarEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200)),
                ('texto', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
