# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.CharField(max_length=800, verbose_name='Descrição')),
                ('create_date', models.DateField(default=datetime.datetime(2018, 2, 22, 18, 47, 56, 937331, tzinfo=utc), verbose_name='Criado em')),
            ],
        ),
        migrations.CreateModel(
            name='Depoimentos',
            fields=[
                ('campos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Campos')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
            ],
            bases=('core.campos',),
        ),
        migrations.CreateModel(
            name='Portifolio',
            fields=[
                ('campos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Campos')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
            options={
                'verbose_name_plural': 'Portfólio',
            },
            bases=('core.campos',),
        ),
        migrations.CreateModel(
            name='QuemSomos',
            fields=[
                ('campos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Campos')),
            ],
            options={
                'verbose_name_plural': 'Quem Somos',
            },
            bases=('core.campos',),
        ),
    ]
