# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 05:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
            ],
            options={
                'verbose_name_plural': 'Correio',
            },
        ),
        migrations.CreateModel(
            name='VejaMais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Quem Somos',
            },
        ),
        migrations.AddField(
            model_name='parceiros',
            name='link',
            field=models.CharField(default='', max_length=100, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='portifolio',
            name='link',
            field=models.CharField(default='', max_length=100, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 6, 5, 6, 3, 797067, tzinfo=utc), verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='descricao',
            field=models.CharField(blank=True, max_length=800, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título'),
        ),
    ]
