# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 20:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiros',
            name='link',
            field=models.CharField(default='', max_length=100, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2018, 2, 27, 20, 21, 55, 723604, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
