# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 01:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180227_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='portifolio',
            name='link',
            field=models.CharField(default='', max_length=100, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2018, 2, 28, 1, 4, 24, 462566, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
