# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 20:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180227_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
            ],
            options={
                'verbose_name_plural': 'Correio',
            },
        ),
        migrations.AlterField(
            model_name='campo',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 7, 20, 12, 7, 409309, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
