# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-13 23:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180307_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 13, 23, 1, 44, 576556, tzinfo=utc), verbose_name='Criado em'),
        ),
    ]
