# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='link',
            field=models.URLField(max_length=500, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='order',
            field=models.IntegerField(unique=True, verbose_name='Ordem de apresentação do slide'),
        ),
    ]
